### ISSUE TITLE
Attempting to navigate to settings page yields error

### ISSUE THREAD

**Issue by KingGamingYT** [pdelfan/ouranos#2]
Everything else will load perfectly fine, but the settings page will always throw a "server-side exception" application error.
![image](https://github.com/pdelfan/ouranos/assets/45918062/d30125f3-a505-4e63-9240-7da5e1d0beee)

**Comment by pdelfan** [comment]
Hi @KingGamingYT, thanks for letting me know. Could you answer a few things to help me have a closer at this?
- Do you have any invite codes (or did, before Bluesky removed them)?
- Which platform and web browser are you using?
- Is your account verified?

Thanks!

**Comment by KingGamingYT** [comment]
> Hi @KingGamingYT, thanks for letting me know. Could you answer a few things to help me have a closer at this?
> 
> * Do you have any invite codes (or did, before Bluesky removed them)?
> * Which platform and web browser are you using?
> * Is your account verified?
> 
> Thanks!

Hi!

1. Yes, I have 5 invite codes, even after Bluesky's discontinuation of them (though I can't use them anymore it seems).

2. I tried both an older gecko-based browser (Firefox) and an up-to-date version of Google Chrome, and both yielded the same result.

3. Yes, my account is email-verified.

**Comment by pdelfan** [comment]
Thanks @KingGamingYT! One more question, what operating system are you using? Since the error is server-side, there probably won't be any errors in your brower's console, but please do check that just in case. I can also check the logs but it only retains the ones from the last hour. Let me know when you're able to replicate it so I can save the log before it disappears.

**Comment by KingGamingYT** [comment]
> Thanks @KingGamingYT! One more question, what operating system are you using? Since the error is server-side, there probably won't be any errors in your brower's console, but please do check that just in case. I can also check the logs but it only retains the ones from the last hour. Let me know when you're able to replicate it so I can save the log before it disappears.

I'm using Windows 10, specifically version 22H2 (19045.3570).

**Comment by pdelfan** [comment]
Thanks again! I'll investigate this soon and will let you know. If it doesn't work out, I'll let you know so you can visit the settings page at an arranged time so I can record the error from Vercel before it disappears.

**Comment by pdelfan** [comment]
Hi @KingGamingYT, could you check and see if the problem persists? If that's the case, I'd appreciate it if you could visit the settings page so I could check the logs.

**Comment by KingGamingYT** [comment]
> Hi @KingGamingYT, could you check and see if the problem persists? If that's the case, I'd appreciate it if you could visit the settings page so I could check the logs. If it's possible, it'd be helpful to do so a few hours after you've seen this message, so I would have time to record it before it disappears.

The problem persists. I hope this is a recent enough response!

**Comment by pdelfan** [comment]
Hi @KingGamingYT, the problem should be fixed now, please sign in again and let me know if you can access the settings page now. 

The issue was that invite codes can't be accessed if you're signed in with an app password. There's a way to check whether you're using an app password, but I decided to remove the invite codes section from the settings page since they're not required anymore.

**Comment by KingGamingYT** [comment]
Can confirm that the problem is fixed! Thanks for all your cooperation.

**Comment by pdelfan** [comment]
Great! Thanks for all your input!
